// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AddressObject struct {
	ID         int32       `json:"id"`
	ObjectID   int32       `json:"object_id"`
	ObjectGuid pgtype.UUID `json:"object_guid"`
	ChangeID   pgtype.Int4 `json:"change_id"`
	Name       pgtype.Text `json:"name"`
	TypeName   pgtype.Text `json:"type_name"`
	Level      pgtype.Int2 `json:"level"`
	OperTypeID pgtype.Int2 `json:"oper_type_id"`
	PrevID     pgtype.Int4 `json:"prev_id"`
	NextID     pgtype.Int4 `json:"next_id"`
	UpdateDate pgtype.Date `json:"update_date"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	IsActual   bool        `json:"is_actual"`
	IsActive   bool        `json:"is_active"`
}

type AddressObjectType struct {
	ID         int32       `json:"id"`
	Level      pgtype.Int4 `json:"level"`
	Name       pgtype.Text `json:"name"`
	ShortName  pgtype.Text `json:"short_name"`
	Desc       pgtype.Text `json:"desc"`
	UpdateDate pgtype.Date `json:"update_date"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	IsActive   pgtype.Bool `json:"is_active"`
}

type AdmHierarchy struct {
	ID          int32       `json:"id"`
	ObjectID    pgtype.Int4 `json:"object_id"`
	ParentObjID pgtype.Int4 `json:"parent_obj_id"`
	ChangeID    pgtype.Int4 `json:"change_id"`
	RegionCode  pgtype.Int4 `json:"region_code"`
	PrevID      pgtype.Int4 `json:"prev_id"`
	NextID      pgtype.Int4 `json:"next_id"`
	UpdateDate  pgtype.Date `json:"update_date"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	IsActive    pgtype.Bool `json:"is_active"`
	Path        pgtype.Text `json:"path"`
}

type ApartmentType struct {
	ID         int32       `json:"id"`
	Name       pgtype.Text `json:"name"`
	ShortName  pgtype.Text `json:"short_name"`
	Desc       pgtype.Text `json:"desc"`
	IsActive   pgtype.Bool `json:"is_active"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	UpdateDate pgtype.Date `json:"update_date"`
}

type HouseType struct {
	ID         int32       `json:"id"`
	Name       pgtype.Text `json:"name"`
	ShortName  pgtype.Text `json:"short_name"`
	Desc       pgtype.Text `json:"desc"`
	IsActive   pgtype.Bool `json:"is_active"`
	UpdateDate pgtype.Date `json:"update_date"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type Migration struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NdocKind struct {
	ID   int32       `json:"id"`
	Name pgtype.Text `json:"name"`
}

type NdocType struct {
	ID        int32       `json:"id"`
	Name      pgtype.Text `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ObjectLevel struct {
	Level      int32       `json:"level"`
	Name       pgtype.Text `json:"name"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	UpdateDate pgtype.Date `json:"update_date"`
	IsActive   pgtype.Bool `json:"is_active"`
}

type OperationType struct {
	ID         int32       `json:"id"`
	Name       pgtype.Text `json:"name"`
	IsActive   pgtype.Bool `json:"is_active"`
	UpdateDate pgtype.Date `json:"update_date"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type Param struct {
	ID          int32       `json:"id"`
	ObjectID    int32       `json:"object_id"`
	ChangeID    pgtype.Int4 `json:"change_id"`
	ChangeIDEnd pgtype.Int4 `json:"change_id_end"`
	TypeID      pgtype.Int2 `json:"type_id"`
	Value       pgtype.Text `json:"value"`
	UpdateDate  pgtype.Date `json:"update_date"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

type ParamType struct {
	ID         int32       `json:"id"`
	Name       pgtype.Text `json:"name"`
	Desc       pgtype.Text `json:"desc"`
	Code       pgtype.Text `json:"code"`
	IsActive   pgtype.Bool `json:"is_active"`
	UpdateDate pgtype.Date `json:"update_date"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type RoomType struct {
	ID         int32       `json:"id"`
	Name       pgtype.Text `json:"name"`
	Desc       pgtype.Text `json:"desc"`
	IsActive   pgtype.Bool `json:"is_active"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	UpdateDate pgtype.Date `json:"update_date"`
}

type VersionInfo struct {
	ID             int32              `json:"id"`
	VersionID      int64              `json:"version_id"`
	TextVersion    string             `json:"text_version"`
	GarXmlFullUrl  pgtype.Text        `json:"gar_xml_full_url"`
	GarXmlDeltaUrl pgtype.Text        `json:"gar_xml_delta_url"`
	ExpDate        pgtype.Timestamp   `json:"exp_date"`
	Date           pgtype.Date        `json:"date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Status         pgtype.Text        `json:"status"`
	FileType       string             `json:"file_type"`
}
