// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAddressObjects = `-- name: CountAddressObjects :one
SELECT count(*)
FROM address_objects
`

func (q *Queries) CountAddressObjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressObjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const extractionBlocker = `-- name: ExtractionBlocker :one
SELECT version_id, status
FROM version_info
WHERE (version_id = $1 AND status IN ('extracted', 'imported'))
   OR (version_id <> $1 AND status = 'extracted' AND file_type = $2)
ORDER BY (version_id = $1) DESC, updated_at DESC
LIMIT 1
`

type ExtractionBlockerRow struct {
	VersionID int64       `json:"version_id"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) ExtractionBlocker(ctx context.Context, versionID int64, fileType string) (ExtractionBlockerRow, error) {
	row := q.db.QueryRow(ctx, extractionBlocker, versionID, fileType)
	var i ExtractionBlockerRow
	err := row.Scan(&i.VersionID, &i.Status)
	return i, err
}

const getVersionInfo = `-- name: GetVersionInfo :one
SELECT id, version_id, text_version, gar_xml_full_url, gar_xml_delta_url, exp_date, date, created_at, updated_at, status, file_type
FROM version_info
WHERE version_id = $1
`

func (q *Queries) GetVersionInfo(ctx context.Context, versionID int64) (VersionInfo, error) {
	row := q.db.QueryRow(ctx, getVersionInfo, versionID)
	var i VersionInfo
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.TextVersion,
		&i.GarXmlFullUrl,
		&i.GarXmlDeltaUrl,
		&i.ExpDate,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.FileType,
	)
	return i, err
}

const upsertVersionInfo = `-- name: UpsertVersionInfo :exec
INSERT INTO version_info (version_id, text_version, gar_xml_full_url, gar_xml_delta_url, exp_date, date, status, file_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (version_id) DO UPDATE
SET text_version      = EXCLUDED.text_version,
    gar_xml_full_url  = EXCLUDED.gar_xml_full_url,
    gar_xml_delta_url = EXCLUDED.gar_xml_delta_url,
    exp_date          = EXCLUDED.exp_date,
    date              = EXCLUDED.date,
    status            = EXCLUDED.status,
    file_type         = EXCLUDED.file_type,
    updated_at        = now()
`

type UpsertVersionInfoParams struct {
	VersionID      int64            `json:"version_id"`
	TextVersion    string           `json:"text_version"`
	GarXmlFullUrl  pgtype.Text      `json:"gar_xml_full_url"`
	GarXmlDeltaUrl pgtype.Text      `json:"gar_xml_delta_url"`
	ExpDate        pgtype.Timestamp `json:"exp_date"`
	Date           pgtype.Date      `json:"date"`
	Status         pgtype.Text      `json:"status"`
	FileType       string           `json:"file_type"`
}

func (q *Queries) UpsertVersionInfo(ctx context.Context, arg UpsertVersionInfoParams) error {
	_, err := q.db.Exec(ctx, upsertVersionInfo,
		arg.VersionID,
		arg.TextVersion,
		arg.GarXmlFullUrl,
		arg.GarXmlDeltaUrl,
		arg.ExpDate,
		arg.Date,
		arg.Status,
		arg.FileType,
	)
	return err
}

const versionImported = `-- name: VersionImported :one
SELECT EXISTS(
    SELECT 1
    FROM version_info
    WHERE version_id = $1 AND status = 'imported'
)
`

func (q *Queries) VersionImported(ctx context.Context, versionID int64) (bool, error) {
	row := q.db.QueryRow(ctx, versionImported, versionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
